name: Frances Darwin
favicon: null
layout_spectrum: 0.41036723856814206
typography_spectrum: 0.580649790354073
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.19847879139706492
  lightness: 0.8237499203532934
  saturation: 0.36101741646416485
  rhythmicContrast: 0.9232085428666323
purpose: []
